version: '3.7'
services:
  adminjs-example:
    container_name: adminjs-example
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: adminjs_example
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5439:5432"
    volumes:
      - adminjs_example_db:/var/lib/postgresql/data
volumes:
  adminjs_example_db:
